### ISSUE TITLE
Error when trying to use BirdSpotter on specialised Twitter Dump

### ISSUE THREAD

**Issue by SkyisjustTheBeginning** [rohitram96/BirdSpotter#12]
### Introduction

Hello , I am trying to use BirdSpotter with a Twitter Dump created by me.

### Errror

It shows the following error :
_**json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)**_

The Twitter dump is in jsonl format.

Here is the Twitter Dump - 

`{\ "created_at\ ": \ "Sun Jan 10 23:55:50 0000 2021\ ", \ "id\ ": \ "1348418302952017922, \ "id_str\ ": \ "1348418302952017922\ ", \ "text\ ": \ "RT @Cloudphish: Arlington Board of Realtors\\n#phishing #CyberSecurity #infosec #technology\\nhttps://t.co/EegBr4KviP\ ", \ "truncated\ ": False, \ "entities\ ": {\ "hashtags\ ": [{\ "text\ ": \ "phishing\ ", \ "indices\ ": [44, 53]}, {\ "text\ ": \ "CyberSecurity\ ", \ "indices\ ": [54, 68]}, {\ "text\ ": \ "infosec\ ", \ "indices\ ": [69, 77]}, {\ "text\ ": \ "technology\ ", \ "indices\ ": [78, 89]}], \ "symbols\ ": [], \ "user_mentions\ ": [{\ "screen_name\ ": \ "Cloudphish\ ", \ "name\ ": \ "Cloudphish Anti Phishing\ ", \ "id\ ": 1141376699835330560, \ "id_str\ ": \ "1141376699835330560\ ", \ "indices\ ": [3, 14]}], \ "urls\ ": [{\ "url\ ": \ "https://t.co/EegBr4KviP\ ", \ "expanded_url\ ": \ "https://www.star telegram.com/homes/article248319155.html\ ", \ "display_url\ ": \ "star telegram.com/homes/article2\ ", \ "indices\ ": [90, 113]}]}, \ "source\ ": \ "<a href=\ "https://homeinc.com/\ ", \ "in_reply_to_status_id\ ": None, \ "in_reply_to_status_id_str\ ": None, \ "in_reply_to_user_id\ ": None, \ "in_reply_to_id_str\ ": None, \ "in_reply_to_screen_name\ ": None, \ "user\ ": {\ "id\ ": 1142424032794406912, \ "id_str\ ": \ "1142424032794406912\ ", \ "name\ ": \ "Cyber Security News\ ", \ "screen_name\ ": \ "CyberSecurityN8\ ", \ "location\ ": \ "\ ", \ "description\ ": \ "The place for InfoSec, CyberSecurity, DevSecOps, DataSecurity and many more!!! Stay tuned.\ ", \ "url\ ": None, \ "entities\ ": {\ "description\ ": {\ "urls\ ": []}}, \ "protected\ ": False, \ "followers_count\ ": 25712, \ "friends_count\ ": 2, \ "listed_count\ ": 349, \ "created_at\ ": \ "Sat Jun 22 13:28:09 0000 2019\ ", \ "favourites_count\ ": 0, \ "utc_offset\ ": None, \ "time_zone\ ": None, \ "geo_enabled\ ": False, \ "verified\ ": False, \ "statuses_count\ ": 1187335, \ "lang\ ": None, \ "contributors_enabled\ ": False, \ "is_translator\ ": False, \ "is_translation_enabled\ ": False, \ "profile_background_color\ ": \ "F5F8FA\ ", \ "profile_background_image_url\ ": None, \ "profile_background_image_url_https\ ": None, \ "profile_background_tile\ ": False, \ "profile_image_url\ ": \ "http://pbs.twimg.com/profile_images/1197135188473475074/8svI 1EO_normal.jpg\ ", \ "profile_image_url_https\ ": \ "https://pbs.twimg.com/profile_images/1197135188473475074/8svI 1EO_normal.jpg\ ", \ "profile_banner_url\ ": \ "https://pbs.twimg.com/profile_banners/1142424032794406912/1574254287\ ", \ "profile_link_color\ ": \ "1DA1F2\ ", \ "profile_sidebar_border_color\ ": \ "C0DEED\ ", \ "profile_sidebar_fill_color\ ": \ "DDEEF6\ ", \ "profile_text_color\ ": \ "333333\ ", \ "profile_use_background_image\ ": True, \ "has_extended_profile\ ": False, \ "default_profile\ ": True, \ "default_profile_image\ ": False, \ "following\ ": False, \ "follow_request_sent\ ": False, \ "notifications\ ": False, \ "translator_type\ ": \ "none\ ", \ "withheld_in_countries\ ": []}, \ "geo\ ": None, \ "coordinates\ ": None, \ "place\ ": None, \ "contributors\ ": None, \ "is_quote_status\ ": False, \ "retweet_count\ ": 19, \ "favorite_count\ ": 0, \ "favorited\ ": False, \ "retweeted\ ": False, \ "possibly_sensitive\ ": False, \ "possibly_sensitive_appealable\ ": False, \ "lang\ ": \ "en\ ", \ "user_id\ ": 1348418306215211013, \ "retweeted_status\ ": {\ "created_at\ ": \ "Sun Jan 10 23:55:37 +0000 2021\ ", \ "id\ ": 1348418248770015232, \ "id_str\ ": \ "1348418248770015232\ ", \ "text\ ": \ "Arlington Board of Realtors\\n#phishing #CyberSecurity #infosec #technology\\nhttps://t.co/EegBr4KviP\ ", \ "truncated\ ": False, \ "entities\ ": {\ "hashtags\ ": [{\ "text\ ": \ "phishing\ ", \ "indices\ ": [28, 37]}, {\ "text\ ": \ "CyberSecurity\ ", \ "indices\ ": [38, 52]}, {\ "text\ ": \ "infosec\ ", \ "indices\ ": [53, 61]}, {\ "text\ ": \ "technology\ ", \ "indices\ ": [62, 73]}], \ "symbols\ ": [], \ "user_mentions\ ": [], \ "urls\ ": [{\ "url\ ": \ "https://t.co/EegBr4KviP\ ", \ "expanded_url\ ": \ "https://www.startelegram.com/homes/article248319155.html\ ", \ "display_url\ ": \ "star telegram.com/homes/article2\ ", \ "indices\ ": [74, 97]}]}, \ "source\ ": \ "<a href=\ "https://cloudphish.com/\ ", \ "in_reply_to_status_id\ ": None, \ "in_reply_to_status_id_str\ ": None, \ "in_reply_to_user_id\ ": None, \ "in_reply_to_id_str\ ": None, \ "in_reply_to_screen_name\ ": None, \ "user\ ": {\ "id\ ": 1141376699835330560, \ "id_str\ ": \ "1141376699835330560\ ", \ "name\ ": \ "Cloudphish Anti Phishing\ ", \ "screen_name\ ": \ "Cloudphish\ ", \ "location\ ": \ "Bedford, MA\ ", \ "description\ ": \ "Cloudphish provides cloud based email validation protecting against all forms of email phishing like spear phishing, spoofing, impersonation and ceo fraud. \ud83d\udee1\ufe0f\ ", \ "url\ ": \ "https://t.co/FL4MKWEFHE\ ", \ "entities\ ": {\ "url\ ": {\ "urls\ ": [{\ "url\ ": \ "https://t.co/FL4MKWEFHE\ ", \ "expanded_url\ ": \ "https://cloudphish.com\ ", \ "display_url\ ": \ "cloudphish.com\ ", \ "indices\ ": [0, 23]}]}, \ "description\ ": {\ "urls\ ": []}}, \ "protected\ ": False, \ "followers_count\ ": 30, \ "friends_count\ ": 123, \ "listed_count\ ": 1, \ "created_at\ ": \ "Wed Jun 19 16:06:25 0000 2019\ ", \ "favourites_count\ ": 29, \ "utc_offset\ ": None, \ "time_zone\ ": None, \ "geo_enabled\ ": False, \ "verified\ ": False, \ "statuses_count\ ": 650, \ "lang\ ": None, \ "contributors_enabled\ ": False, \ "is_translator\ ": False, \ "is_translation_enabled\ ": False, \ "profile_background_color\ ": \ "000000\ ", \ "profile_background_image_url\ ": \ "http://abs.twimg.com/images/themes/theme1/bg.png\ ", \ "profile_background_image_url_https\ ": \ "https://abs.twimg.com/images/themes/theme1/bg.png\ ", \ "profile_background_tile\ ": False, \ "profile_image_url\ ": \ "http://pbs.twimg.com/profile_images/1141377536699637766/hVGGx0Ju_normal.png\ ", \ "profile_image_url_https\ ": \ "https://pbs.twimg.com/profile_images/1141377536699637766/hVGGx0Ju_normal.png\ ", \ "profile_banner_url\ ": \ "https://pbs.twimg.com/profile_banners/1141376699835330560/1560960628\ ", \ "profile_link_color\ ": \ "673AB7\ ", \ "profile_sidebar_border_color\ ": \ "000000\ ", \ "profile_sidebar_fill_color\ ": \ "000000\ ", \ "profile_text_color\ ": \ "000000\ ", \ "profile_use_background_image\ ": False, \ "has_extended_profile\ ": True, \ "default_profile\ ": False, \ "default_profile_image\ ": False, \ "following\ ": False, \ "follow_request_sent\ ": False, \ "notifications\ ": False, \ "translator_type\ ": \ "none\ ", \ "withheld_in_countries\ ": []}, \ "geo\ ": None, \ "coordinates\ ": None, \ "place\ ": None, \ "contributors\ ": None, \ "is_quote_status\ ": False, \ "retweet_count\ ": 2, \ "favorite_count\ ": 0, \ "favorited\ ": False, \ "retweeted\ ": False, \ "possibly_sensitive\ ": False, \ "possibly_sensitive_appealable\ ": False, \ "lang\ ": \ "en\ "}}`

This is the BirdSpotter code:

`from birdspotter import BirdSpotter
import ast
import json
import logging
input2 = str(input('File : '))
logging.basicConfig(level=logging.DEBUG)
bs = BirdSpotter(input2)
labeledUsers = bs.getLabeledUsers(out='./output.csv')
cascades = bs.getCascadesDataFrame()
bs.featureDataframe[['screen_name', 'botness']].sort_values(by='botness', ascending=False)
print('No Errors')`

I would be really grateful if I got a quick response.

Thanks in advance

**Comment by rohitram96** [comment]
Hi Jon,
Birdspotter utilizes the python `json` module internally, to load jsonl. It cannot deal with the escaped marks (i.e. `\ "`) you have in the json. You'll need to fix this for it to work. You might find `json.dumps` useful if you have a version of the data in python.

Let me know how you go

**Comment by SkyisjustTheBeginning** [comment]
I will try your suggestion.Thanks for the quick response !

**Comment by SkyisjustTheBeginning** [comment]
@rohitram96 I got a new error :

_**ERROR : Expecting value: line 1 column 264 (char 263)
**_

Here is my updated json lines file - 

`{ "created_at ":  "Sun Jan 10 23:55:50 0000 2021 ",  "id ":  1348418302952017922,  "id_str ":  "1348418302952017922 ",  "text ":  "RT @Cloudphish: Arlington Board of Realtorsn#phishing #CyberSecurity #infosec #technologynhttps://t.co/EegBr4KviP ",  "truncated ": False,  "entities ": { "hashtags ": [{ "text ":  "phishing ",  "indices ": [44, 53]}, { "text ":  "CyberSecurity ",  "indices ": [54, 68]}, { "text ":  "infosec ",  "indices ": [69, 77]}, { "text ":  "technology ",  "indices ": [78, 89]}],  "symbols ": [],  "user_mentions ": [{ "screen_name ":  "Cloudphish ",  "name ":  "Cloudphish Anti Phishing ",  "id ": 1141376699835330560,  "id_str ":  "1141376699835330560 ",  "indices ": [3, 14]}],  "urls ": [{ "url ":  "https://t.co/EegBr4KviP ",  "expanded_url ":  "https://www.star telegram.com/homes/article248319155.html ",  "display_url ":  "star telegram.com/homes/article2 ",  "indices ": [90, 113]}]},  "source ":  "<a href= "https://homeinc.com/ ",  "in_reply_to_status_id ": None,  "in_reply_to_status_id_str ": None,  "in_reply_to_user_id ": None,  "in_reply_to_id_str ": None,  "in_reply_to_screen_name ": None,  "user ": { "id ": 1142424032794406912,  "id_str ":  "1142424032794406912 ",  "name ":  "Cyber Security News ",  "screen_name ":  "CyberSecurityN8 ",  "location ":  " ",  "description ":  "The place for InfoSec, CyberSecurity, DevSecOps, DataSecurity and many more!!! Stay tuned. ",  "url ": None,  "entities ": { "description ": { "urls ": []}},  "protected ": False,  "followers_count ": 25712,  "friends_count ": 2,  "listed_count ": 349,  "created_at ":  "Sat Jun 22 13:28:09 0000 2019 ",  "favourites_count ": 0,  "utc_offset ": None,  "time_zone ": None,  "geo_enabled ": False,  "verified ": False,  "statuses_count ": 1187335,  "lang ": None,  "contributors_enabled ": False,  "is_translator ": False,  "is_translation_enabled ": False,  "profile_background_color ":  "F5F8FA ",  "profile_background_image_url ": None,  "profile_background_image_url_https ": None,  "profile_background_tile ": False,  "profile_image_url ":  "http://pbs.twimg.com/profile_images/1197135188473475074/8svI 1EO_normal.jpg ",  "profile_image_url_https ":  "https://pbs.twimg.com/profile_images/1197135188473475074/8svI 1EO_normal.jpg ",  "profile_banner_url ":  "https://pbs.twimg.com/profile_banners/1142424032794406912/1574254287 ",  "profile_link_color ":  "1DA1F2 ",  "profile_sidebar_border_color ":  "C0DEED ",  "profile_sidebar_fill_color ":  "DDEEF6 ",  "profile_text_color ":  "333333 ",  "profile_use_background_image ": True,  "has_extended_profile ": False,  "default_profile ": True,  "default_profile_image ": False,  "following ": False,  "follow_request_sent ": False,  "notifications ": False,  "translator_type ":  "none ",  "withheld_in_countries ": []},  "geo ": None,  "coordinates ": None,  "place ": None,  "contributors ": None,  "is_quote_status ": False,  "retweet_count ": 19,  "favorite_count ": 0,  "favorited ": False,  "retweeted ": False,  "possibly_sensitive ": False,  "possibly_sensitive_appealable ": False,  "lang ":  "en ",  "user_id ": 1348418306215211013,  "retweeted_status ": { "created_at ":  "Sun Jan 10 23:55:37 +0000 2021 ",  "id ": 1348418248770015232,  "id_str ":  "1348418248770015232 ",  "text ":  "Arlington Board of Realtorsn#phishing #CyberSecurity #infosec #technologynhttps://t.co/EegBr4KviP ",  "truncated ": False,  "entities ": { "hashtags ": [{ "text ":  "phishing ",  "indices ": [28, 37]}, { "text ":  "CyberSecurity ",  "indices ": [38, 52]}, { "text ":  "infosec ",  "indices ": [53, 61]}, { "text ":  "technology ",  "indices ": [62, 73]}],  "symbols ": [],  "user_mentions ": [],  "urls ": [{ "url ":  "https://t.co/EegBr4KviP ",  "expanded_url ":  "https://www.startelegram.com/homes/article248319155.html ",  "display_url ":  "star telegram.com/homes/article2 ",  "indices ": [74, 97]}]},  "source ":  "<a href= "https://cloudphish.com/ ",  "in_reply_to_status_id ": None,  "in_reply_to_status_id_str ": None,  "in_reply_to_user_id ": None,  "in_reply_to_id_str ": None,  "in_reply_to_screen_name ": None,  "user ": { "id ": 1141376699835330560,  "id_str ":  "1141376699835330560 ",  "name ":  "Cloudphish Anti Phishing ",  "screen_name ":  "Cloudphish ",  "location ":  "Bedford, MA ",  "description ":  "Cloudphish provides cloud based email validation protecting against all forms of email phishing like spear phishing, spoofing, impersonation and ceo fraud. ud83dudee1ufe0f ",  "url ":  "https://t.co/FL4MKWEFHE ",  "entities ": { "url ": { "urls ": [{ "url ":  "https://t.co/FL4MKWEFHE ",  "expanded_url ":  "https://cloudphish.com ",  "display_url ":  "cloudphish.com ",  "indices ": [0, 23]}]},  "description ": { "urls ": []}},  "protected ": False,  "followers_count ": 30,  "friends_count ": 123,  "listed_count ": 1,  "created_at ":  "Wed Jun 19 16:06:25 0000 2019 ",  "favourites_count ": 29,  "utc_offset ": None,  "time_zone ": None,  "geo_enabled ": False,  "verified ": False,  "statuses_count ": 650,  "lang ": None,  "contributors_enabled ": False,  "is_translator ": False,  "is_translation_enabled ": False,  "profile_background_color ":  "000000 ",  "profile_background_image_url ":  "http://abs.twimg.com/images/themes/theme1/bg.png ",  "profile_background_image_url_https ":  "https://abs.twimg.com/images/themes/theme1/bg.png ",  "profile_background_tile ": False,  "profile_image_url ":  "http://pbs.twimg.com/profile_images/1141377536699637766/hVGGx0Ju_normal.png ",  "profile_image_url_https ":  "https://pbs.twimg.com/profile_images/1141377536699637766/hVGGx0Ju_normal.png ",  "profile_banner_url ":  "https://pbs.twimg.com/profile_banners/1141376699835330560/1560960628 ",  "profile_link_color ":  "673AB7 ",  "profile_sidebar_border_color ":  "000000 ",  "profile_sidebar_fill_color ":  "000000 ",  "profile_text_color ":  "000000 ",  "profile_use_background_image ": False,  "has_extended_profile ": True,  "default_profile ": False,  "default_profile_image ": False,  "following ": False,  "follow_request_sent ": False,  "notifications ": False,  "translator_type ":  "none ",  "withheld_in_countries ": []},  "geo ": None,  "coordinates ": None,  "place ": None,  "contributors ": None,  "is_quote_status ": False,  "retweet_count ": 2,  "favorite_count ": 0,  "favorited ": False,  "retweeted ": False,  "possibly_sensitive ": False,  "possibly_sensitive_appealable ": False,  "lang ":  "en "} `

**Comment by rohitram96** [comment]
Hi Jon,
Assuming this is all one JSON line; could you try reading it using the `json` module. If it doesn't work, then this is not valid JSON, and it'll need to be formatted.

**Comment by SkyisjustTheBeginning** [comment]
Will do.

Ps.It is all in one line

**Comment by SkyisjustTheBeginning** [comment]
It is working now.

THanks for the help !

**Comment by SkyisjustTheBeginning** [comment]
Closing since error is fixed.
