### ISSUE TITLE
ValueError: empty vocabulary; perhaps the documents only contain stop words

### ISSUE THREAD

**Issue by SkyisjustTheBeginning** [rohitram96/BirdSpotter#13]
Yes.I am back.

I was trying to use BirdSpotter with another Twitter dump and I got this error.

This is my jsonl file - 
### 
MY JSON FILE

`{"created_at": "Sun Jan 10 23:57:57 +0000 2021", "id": 1348418836060643332, "id_str": "1348418836060643332", "text": "RT @randomsakuga: Key Animation: https://t.co/Rl0OlpzfN6\nSeries: Rise of the Teenage Mutant Ninja Turtles (2019)\n\nhttps://t.co/LhTssYyf3A h…", "truncated": false, "entities": {"hashtags": [], "symbols": [], "user_mentions": [{"screen_name": "randomsakuga", "name": "randomsakuga", "id": 835969639851126784, "id_str": "835969639851126784", "indices": [3, 16]}], "urls": [{"url": "https://t.co/Rl0OlpzfN6", "expanded_url": "https://pastebin.com/raw/tqwCF1Ue", "display_url": "pastebin.com/raw/tqwCF1Ue", "indices": [33, 56]}, {"url": "https://t.co/LhTssYyf3A", "expanded_url": "https://www.sakugabooru.com/post/show/107024", "display_url": "sakugabooru.com/post/show/1070…", "indices": [114, 137]}]}, "source": "<a href='http://twitter.com/download/android' rel='nofollow'>Twitter for Android</a>", "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 2809289914, "id_str": "2809289914", "name": "peppy ", "screen_name": "fluttershoot", "location": "she/they whtvr!  23", "description": "hi im peppy!  goblin, goth, clown, monster, freak enthusiast  this is my personal twitter so i post everything! || pfp by @EliseraArt ", "url": null, "entities": {"description": {"urls": []}}, "protected": false, "followers_count": 628, "friends_count": 2396, "listed_count": 4, "created_at": "Sun Oct 05 23:02:50 +0000 2014", "favourites_count": 80025, "utc_offset": null, "time_zone": null, "geo_enabled": false, "verified": false, "statuses_count": 10299, "lang": null, "contributors_enabled": false, "is_translator": false, "is_translation_enabled": false, "profile_background_color": "C0DEED", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_tile": false, "profile_image_url": "http://pbs.twimg.com/profile_images/1386826629217927168/OcENzEZW_normal.jpg", "profile_image_url_https": "https://pbs.twimg.com/profile_images/1386826629217927168/OcENzEZW_normal.jpg", "profile_banner_url": "https://pbs.twimg.com/profile_banners/2809289914/1629929357", "profile_link_color": "1DA1F2", "profile_sidebar_border_color": "C0DEED", "profile_sidebar_fill_color": "DDEEF6", "profile_text_color": "333333", "profile_use_background_image": true, "has_extended_profile": true, "default_profile": true, "default_profile_image": false, "following": false, "follow_request_sent": false, "notifications": false, "translator_type": "null", "withheld_in_countries": []}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweeted_status": {"created_at": "Sun Jan 10 17:00:40 +0000 2021", "id": 1348313822810013708, "id_str": "1348313822810013708", "text": "Key Animation: https://t.co/Rl0OlpzfN6\nSeries: Rise of the Teenage Mutant Ninja Turtles (2019)… https://t.co/iBxNCrJNYp", "truncated": true, "entities": {"hashtags": [], "symbols": [], "user_mentions": [], "urls": [{"url": "https://t.co/Rl0OlpzfN6", "expanded_url": "https://pastebin.com/raw/tqwCF1Ue", "display_url": "pastebin.com/raw/tqwCF1Ue", "indices": [15, 38]}, {"url": "https://t.co/iBxNCrJNYp", "expanded_url": "https://twitter.com/i/web/status/1348313822810013708", "display_url": "twitter.com/i/web/status/1…", "indices": [96, 119]}]}, "source": "<a href='https://www.hootsuite.com' rel='nofollow'>Hootsuite Inc.</a>", "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 835969639851126784, "id_str": "835969639851126784", "name": "randomsakuga", "screen_name": "randomsakuga", "location": "", "description": "Providing some good animation on your timeline. The medias are taken from @sakugabooru", "url": "https://t.co/vw6ZEEYgAU", "entities": {"url": {"urls": [{"url": "https://t.co/vw6ZEEYgAU", "expanded_url": "https://sakugabooru.com/post", "display_url": "sakugabooru.com/post", "indices": [0, 23]}]}, "description": {"urls": []}}, "protected": false, "followers_count": 258337, "friends_count": 33, "listed_count": 1618, "created_at": "Sun Feb 26 21:47:48 +0000 2017", "favourites_count": 6, "utc_offset": null, "time_zone": null, "geo_enabled": false, "verified": true, "statuses_count": 9668, "lang": null, "contributors_enabled": false, "is_translator": false, "is_translation_enabled": false, "profile_background_color": "000000", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_tile": false, "profile_image_url": "http://pbs.twimg.com/profile_images/840302059362615296/TaVA2uei_normal.jpg", "profile_image_url_https": "https://pbs.twimg.com/profile_images/840302059362615296/TaVA2uei_normal.jpg", "profile_banner_url": "https://pbs.twimg.com/profile_banners/835969639851126784/1489177763", "profile_link_color": "ABB8C2", "profile_sidebar_border_color": "000000", "profile_sidebar_fill_color": "000000", "profile_text_color": "000000", "profile_use_background_image": false, "has_extended_profile": false, "default_profile": false, "default_profile_image": false, "following": false, "follow_request_sent": false, "notifications": false, "translator_type": "null", "withheld_in_countries": []}, "geo": null, "coordinates": null, "place": null, "contributors": null, "is_quote_status": false, "retweet_count": 2009, "favorite_count": 8910, "favorited": false, "retweeted": false, "possibly_sensitive": false, "possibly_sensitive_appealable": false, "lang": "en"}, "is_quote_status": false, "retweet_count": 2009, "favorite_count": 0, "favorited": false, "retweeted": false, "possibly_sensitive": false, "possibly_sensitive_appealable": false, "lang": "en"}`

**Comment by SkyisjustTheBeginning** [comment]
Would appreciate a swift response.

Thanks in advance

**Comment by SkyisjustTheBeginning** [comment]
Update : I assumed that my json lines file had a lot of stop words and I ran a Python program which removes stop words.

This is the updated JSONL file

### JSON FILE

`{"created_at": "Sun Jan 10 23:57:57 +0000 2021", "id": 1348418836060643332, "id_str": "1348418836060643332", "text": "RT @randomsakuga: Key Animation: https://t.co/Rl0OlpzfN6Series: Rise Teenage Mutant Ninja Turtles (2019)https://t.co/LhTssYyf3A ", "truncated": false, "entities": {"hashtags": [], "symbols": [], "user_mentions": [{"screen_name": "randomsakuga", "name": "randomsakuga", "id": 835969639851126784, "id_str": "835969639851126784", "indices": [3, 16]}], "urls": [{"url": "https://t.co/Rl0OlpzfN6", "expanded_url": "https://pastebin.com/raw/tqwCF1Ue", "display_url": "pastebin.com/raw/tqwCF1Ue", "indices": [33, 56]}, {"url": "https://t.co/LhTssYyf3A", "expanded_url": "https://www.sakugabooru.com/post/show/107024", "display_url": "sakugabooru.com/post/show/1070", "indices": [114, 137]}]}, "source": "<a href='http://twitter.com/download/android' rel='nofollow'>Twitter Android</a>", "in_reply_to_status_id": null, "in_reply_to_status_id_str": "en", "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 2809289914, "id_str": "2809289914", "name": "peppy ", "screen_name": "fluttershoot", "location": null, "description": "hi peppy!  personal twitter post everything! pfp @EliseraArt ", "url": null, "entities": {"description": {"urls": []}}, "protected": false, "followers_count": 628, "friends_count": 2396, "listed_count": 4, "created_at": "Sun Oct 05 23:02:50 +0000 2014", "favourites_count": 80025, "utc_offset": null, "time_zone": null, "geo_enabled": false, "verified": false, "statuses_count": 10299, "lang": null, "contributors_enabled": false, "is_translator": false, "is_translation_enabled": false, "profile_background_color": "C0DEED", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_tile": false, "profile_image_url": "http://pbs.twimg.com/profile_images/1386826629217927168/OcENzEZW_normal.jpg", "profile_image_url_https": "https://pbs.twimg.com/profile_images/1386826629217927168/OcENzEZW_normal.jpg", "profile_banner_url": "https://pbs.twimg.com/profile_banners/2809289914/1629929357", "profile_link_color": "1DA1F2", "profile_sidebar_border_color": "C0DEED", "profile_sidebar_fill_color": "DDEEF6", "profile_text_color": "333333", "profile_use_background_image": true, "has_extended_profile": true, "default_profile": true, "default_profile_image": false, "following": false, "follow_request_sent": false, "notifications": false, "translator_type": "null", "withheld_in_countries": []}, "geo": null, "coordinates": null, "place": null, "contributors": null, "retweeted_status": {"created_at": "Sun Jan 10 17:00:40 +0000 2021", "id": 1348313822810013708, "id_str": "1348313822810013708", "text": "Key Animation: https://t.co/Rl0OlpzfN6 Series: Rise Teenage Mutant Ninja Turtles (2019) https://t.co/iBxNCrJNYp", "truncated": true, "entities": {"hashtags": [], "symbols": [], "user_mentions": [], "urls": [{"url": "https://t.co/Rl0OlpzfN6", "expanded_url": "https://pastebin.com/raw/tqwCF1Ue", "display_url": "pastebin.com/raw/tqwCF1Ue", "indices": [15, 38]}, {"url": "https://t.co/iBxNCrJNYp", "expanded_url": "https://twitter.com/i/web/status/1348313822810013708", "display_url": "twitter.com/i/web/status/1", "indices": [96, 119]}]}, "source": "<a href='https://www.hootsuite.com' rel='nofollow'>Hootsuite Inc.</a>", "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user": {"id": 835969639851126784, "id_str": "835969639851126784", "name": "randomsakuga", "screen_name": "randomsakuga", "location": null, "description": "Providing good animation timeline. The medias taken @sakugabooru", "url": "https://t.co/vw6ZEEYgAU", "entities": {"url": {"urls": [{"url": "https://t.co/vw6ZEEYgAU", "expanded_url": "https://sakugabooru.com/post", "display_url": "sakugabooru.com/post", "indices": [0, 23]}]}, "description": {"urls": []}}, "protected": false, "followers_count": 258337, "friends_count": 33, "listed_count": 1618, "created_at": "Sun Feb 26 21:47:48 +0000 2017", "favourites_count": 6, "utc_offset": null, "time_zone": null, "geo_enabled": false, "verified": true, "statuses_count": 9668, "lang": null, "contributors_enabled": false, "is_translator": false, "is_translation_enabled": false, "profile_background_color": "000000", "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png", "profile_background_tile": false, "profile_image_url": "http://pbs.twimg.com/profile_images/840302059362615296/TaVA2uei_normal.jpg", "profile_image_url_https": "https://pbs.twimg.com/profile_images/840302059362615296/TaVA2uei_normal.jpg", "profile_banner_url": "https://pbs.twimg.com/profile_banners/835969639851126784/1489177763", "profile_link_color": "ABB8C2", "profile_sidebar_border_color": "000000", "profile_sidebar_fill_color": "000000", "profile_text_color": "000000", "profile_use_background_image": false, "has_extended_profile": false, "default_profile": false, "default_profile_image": false, "following": false, "follow_request_sent": false, "notifications": false, "translator_type": "null", "withheld_in_countries": []}, "geo": null, "coordinates": null, "place": null, "contributors": null, "is_quote_status": false, "retweet_count": 2009, "favorite_count": 8910, "favorited": false, "retweeted": false, "possibly_sensitive": false, "possibly_sensitive_appealable": false, "lang": "en"}, "is_quote_status": false, "retweet_count": 2009, "favorite_count": 0, "favorited": false, "retweeted": false, "possibly_sensitive": false, "possibly_sensitive_appealable": false, "lang": "en"}`

**Comment by SkyisjustTheBeginning** [comment]
@rohitram96

**Comment by SkyisjustTheBeginning** [comment]
found the solution

**Comment by rohitram96** [comment]
Hi Jon,
Apologies that I didn't get around to helping you earlier.

Could you briefly describe what the underlying problem was, and your solution? 
(For future reference)

Cheers

**Comment by SkyisjustTheBeginning** [comment]
I am not an expert in using Tweepy but from what I gather , Some of the Tweet IDs led to broken statuses.I removed these broken IDs and the program works fine now.

Ps.Sorry for the late reply !
